name: lolz
description: A new Flutter project.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Flutter dependencies
  cupertino_icons: ^1.0.2

  # HTTP Client Library
  dio: ^5.7.0

  # Shared preferences for local storage
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints
  flutter_lints: ^2.0.0

flutter:
  # Enable Material Icons
  uses-material-design: true

  # Add asset images
  assets:
    - assets/main.png
